use std::process::Command;
use std::path::{Path, PathBuf};
use serde::{Serialize, Deserialize};
use std::fs;
use std::time::UNIX_EPOCH;
use std::collections::HashMap;
use walkdir::WalkDir;
use tauri_plugin_sql::{Migration, MigrationKind};

#[derive(Serialize, Deserialize, Clone)]
pub struct VenvInfo {
    name: String,
    path: String,
    version: String,
    status: String,
    issue: Option<String>,
    last_modified: u64,
    manager_type: String,
}

#[derive(Serialize, Deserialize)]
pub struct VenvDetails {
    packages: Vec<String>,
    size_mb: f64,
}

#[derive(Serialize, Deserialize)]
pub struct OutdatedPackage {
    name: String,
    version: String,
    latest_version: String,
}

// --- Internal Helpers ---

fn get_pip_path(venv_path: &Path) -> PathBuf {
    let mut p = venv_path.to_path_buf();
    #[cfg(windows)] p.push("Scripts/pip.exe");
    #[cfg(not(windows))] p.push("bin/pip");
    p
}

fn get_python_path(venv_path: &Path) -> PathBuf {
    let mut p = venv_path.to_path_buf();
    #[cfg(windows)] p.push("Scripts/python.exe");
    #[cfg(not(windows))] p.push("bin/python");
    p
}

fn get_venv_info(p: &Path) -> Option<VenvInfo> {
    if !p.is_dir() { return None; }
    let cfg_path = p.join("pyvenv.cfg");
    let bin_path = get_python_path(p);

    if cfg_path.exists() || bin_path.exists() {
        let mut status = "Healthy".to_string();
        let mut issue = None;
        let mut version = "Unknown".to_string();
        let last_modified = p.metadata().and_then(|m| m.modified()).map(|t| t.duration_since(UNIX_EPOCH).map(|d| d.as_secs()).unwrap_or(0)).unwrap_or(0);

        if !bin_path.exists() {
            status = "Broken".to_string();
            issue = Some("Missing Python binary".to_string());
        } else {
            let version_output = Command::new(&bin_path).arg("--version").output();
            match version_output {
                Ok(out) if out.status.success() => { version = String::from_utf8_lossy(&out.stdout).trim().to_string(); },
                _ => { status = "Broken".to_string(); issue = Some("Interpreter corrupted".to_string()); }
            }
        }
        let manager_type = if p.join("uv.lock").exists() || p.parent().map_or(false, |parent| parent.join("uv.lock").exists()) {
            "uv".to_string()
        } else {
            "pip".to_string()
        };

        return Some(VenvInfo { 
            name: p.file_name().unwrap_or_default().to_string_lossy().to_string(), 
            path: p.to_string_lossy().to_string(), 
            version, 
            status, 
            issue, 
            last_modified,
            manager_type
        });
    }
    None
}

// --- New Commands for Analysis ---

#[tauri::command]
fn get_package_sizes(venv_path: String) -> Result<HashMap<String, f64>, String> {
    let mut sizes = HashMap::new();
    let p = Path::new(&venv_path);
    
    // Find site-packages directory (logic varies by Python version/OS)
    // On Linux usually: lib/python3.x/site-packages
    #[cfg(not(windows))]
    let lib_dir = p.join("lib");
    #[cfg(windows)]
    let lib_dir = p.join("Lib").join("site-packages");

    #[cfg(not(windows))]
    if let Ok(entries) = fs::read_dir(lib_dir) {
        for entry in entries.flatten() {
            let path = entry.path();
            if path.is_dir() && entry.file_name().to_string_lossy().starts_with("python") {
                let site_pkgs = path.join("site-packages");
                if site_pkgs.exists() {
                    if let Ok(pkg_entries) = fs::read_dir(site_pkgs) {
                        for pkg in pkg_entries.flatten() {
                            let pkg_path = pkg.path();
                            let name = pkg.file_name().to_string_lossy().to_string();
                            if !name.ends_with(".dist-info") && !name.starts_with("__") {
                                let size = fs_extra::dir::get_size(&pkg_path).unwrap_or(0);
                                sizes.insert(name, (size as f64) / 1024.0 / 1024.0);
                            }
                        }
                    }
                }
            }
        }
    }
    
    #[cfg(windows)]
    if lib_dir.exists() {
        if let Ok(pkg_entries) = fs::read_dir(lib_dir) {
            for pkg in pkg_entries.flatten() {
                let pkg_path = pkg.path();
                let name = pkg.file_name().to_string_lossy().to_string();
                if !name.ends_with(".dist-info") && !name.starts_with("__") {
                    let size = fs_extra::dir::get_size(&pkg_path).unwrap_or(0);
                    sizes.insert(name, (size as f64) / 1024.0 / 1024.0);
                }
            }
        }
    }

    Ok(sizes)
}

#[tauri::command]
fn generate_docker_files(_venv_path: String, python_version: String) -> HashMap<String, String> {
    let mut files = HashMap::new();
    let version = python_version.split(' ').last().unwrap_or("3.12");
    
    let dockerfile = format!(
r#"# Generated by PyManager
FROM python:{}-slim

WORKDIR /app

# Install system dependencies if needed
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# Copy requirements and install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project code
COPY . .

# Default execution
CMD ["python", "main.py"]
"#, version);

    let compose = r#"# Generated by PyManager
services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
"#;

    files.insert("Dockerfile".to_string(), dockerfile);
    files.insert("docker-compose.yml".to_string(), compose.to_string());
    files
}

// --- Standard Commands ---

#[tauri::command]
fn check_venv_health(venv_path: String) -> Result<String, String> {
    let pip = get_pip_path(Path::new(&venv_path));
    let out = Command::new(pip).arg("check").output().map_err(|e| e.to_string())?;
    if out.status.success() { Ok("No conflicts found.".into()) } else { Ok(String::from_utf8_lossy(&out.stdout).to_string()) }
}

#[tauri::command]
fn list_outdated_packages(venv_path: String) -> Result<Vec<OutdatedPackage>, String> {
    let pip = get_pip_path(Path::new(&venv_path));
    let out = Command::new(pip).args(["list", "--outdated", "--format=json"]).output().map_err(|e| e.to_string())?;
    if out.status.success() { let pkgs: Vec<OutdatedPackage> = serde_json::from_slice(&out.stdout).map_err(|e| e.to_string())?; Ok(pkgs) } else { Ok(Vec::new()) }
}

#[tauri::command]
fn get_pyvenv_cfg(venv_path: String) -> Result<String, String> {
    let path = Path::new(&venv_path).join("pyvenv.cfg");
    if path.exists() { fs::read_to_string(path).map_err(|e| e.to_string()) } else { Err("pyvenv.cfg not found".into()) }
}

#[tauri::command]
fn list_system_pythons() -> Vec<String> {
    let mut found_versions = HashMap::new(); // version_string -> path
    
    let path_var = std::env::var_os("PATH").unwrap_or_default();
    let paths = std::env::split_paths(&path_var);

    for dir in paths {
        if let Ok(entries) = fs::read_dir(dir) {
            for entry in entries.flatten() {
                let name = entry.file_name().to_string_lossy().to_string();
                let name_low = name.to_lowercase();
                
                // Match: python, python3, python3.x, python.exe, etc.
                // Avoid: python-config, python3-config, pip, etc.
                let is_python = (name_low == "python" || name_low == "python.exe" || 
                                 name_low == "python3" || name_low == "python3.exe" ||
                                 (name_low.starts_with("python3.") && name_low.chars().nth(8).map_or(false, |c| c.is_ascii_digit())))
                                && !name_low.contains("-config");

                if is_python {
                    let p = entry.path();
                    if let Ok(out) = Command::new(&p).arg("--version").output() {
                        if out.status.success() {
                            let version = if out.stdout.is_empty() {
                                String::from_utf8_lossy(&out.stderr)
                            } else {
                                String::from_utf8_lossy(&out.stdout)
                            }.trim().to_string();

                            if !version.is_empty() {
                                // Deduplicate: prefer paths with numbers (specific versions)
                                let current_path = p.to_string_lossy().to_string();
                                if !found_versions.contains_key(&version) || current_path.contains(".") {
                                    found_versions.insert(version, current_path);
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    
    found_versions.into_iter().map(|(v, p)| format!("{}|{}", p, v)).collect()
}

#[tauri::command]
fn run_venv_script(venv_path: String, command: String) -> Result<String, String> {
    let python = get_python_path(Path::new(&venv_path));
    let out = Command::new(python).arg("-c").arg(&command).output().map_err(|e| e.to_string())?;
    if out.status.success() { Ok(String::from_utf8_lossy(&out.stdout).to_string()) } else { Err(String::from_utf8_lossy(&out.stderr).to_string()) }
}

#[tauri::command]
fn read_env_file(venv_path: String) -> Result<String, String> {
    let pb = PathBuf::from(&venv_path);
    let project_root = pb.parent().unwrap_or(Path::new(&venv_path));
    let env_path = project_root.join(".env");
    if env_path.exists() { fs::read_to_string(env_path).map_err(|e| e.to_string()) } else { Ok("".to_string()) }
}

#[tauri::command]
fn save_env_file(venv_path: String, content: String) -> Result<(), String> {
    let pb = PathBuf::from(&venv_path);
    let project_root = pb.parent().unwrap_or(Path::new(&venv_path));
    let env_path = project_root.join(".env");
    fs::write(env_path, content).map_err(|e| e.to_string())
}

#[tauri::command]
fn open_terminal(path: String) -> Result<(), String> {
    #[cfg(target_os = "linux")] {
        let terminal_commands = [("gnome-terminal", vec!["--working-directory"]), ("konsole", vec!["--workdir"]), ("xfce4-terminal", vec!["--working-directory"]), ("xterm", vec!["-cd"])];
        for (term, args) in terminal_commands {
            let mut cmd = Command::new(term);
            for arg in &args { cmd.arg(arg); }
            cmd.arg(&path);
            if cmd.spawn().is_ok() { return Ok(()); }
        }
    }
    #[cfg(target_os = "windows")] { Command::new("cmd").args(["/c", "start", "cmd.exe", "/k", "cd", "/d", &path]).spawn().map_err(|e| e.to_string())?; }
    Ok(())
}

#[tauri::command]
fn open_in_vscode(path: String) -> Result<(), String> {
    let pb = PathBuf::from(&path);
    let parent = pb.parent().unwrap_or(Path::new(&path)).to_string_lossy().to_string();
    #[cfg(target_os = "windows")] { Command::new("cmd").args(["/c", "code", &parent]).spawn().map_err(|e| e.to_string())?; }
    #[cfg(not(target_os = "windows"))] { Command::new("code").arg(&parent).spawn().map_err(|e| e.to_string())?; }
    Ok(())
}

#[tauri::command]
fn scan_venv(path: String) -> Result<VenvInfo, String> {
    get_venv_info(Path::new(&path)).ok_or_else(|| "Not a valid venv".to_string())
}

#[tauri::command]
fn list_venvs(base_path: String) -> Result<Vec<VenvInfo>, String> {
    let mut venvs = Vec::new();
    let root = Path::new(&base_path);
    if !root.is_dir() { return Err("Invalid directory path".to_string()); }
    let walker = WalkDir::new(root).into_iter().filter_entry(|e| {
        let name = e.file_name().to_string_lossy();
        if name == "node_modules" || name == "target" || name == "__pycache__" || name == ".git" { return false; }
        if name.starts_with('.') && name != ".venv" { return false; }
        true
    });
    for entry in walker.filter_map(|e| e.ok()) {
        if let Some(info) = get_venv_info(entry.path()) { venvs.push(info); }
    }
    Ok(venvs)
}

#[derive(Serialize, Deserialize)]
pub struct AuditReport {
    broken_links: Vec<String>, // Paths in DB but not on disk
    untracked_venvs: Vec<VenvInfo>, // Paths on disk but not in DB
}

#[derive(Serialize, Deserialize)]
pub struct ManagerStatus {
    uv: bool,
    poetry: bool,
    pdm: bool,
}

#[tauri::command]
fn audit_environments(workspace_paths: Vec<String>, registered_paths: Vec<String>) -> AuditReport {
    let mut broken_links = Vec::new();
    let mut untracked_venvs = Vec::new();

    // 1. Check for Broken Links (DB entries without physical folder)
    for path in &registered_paths {
        if !Path::new(path).exists() {
            broken_links.push(path.clone());
        }
    }

    // 2. Check for Untracked Venvs (Folders on disk not in DB)
    for ws in workspace_paths {
        let root = Path::new(&ws);
        if !root.is_dir() { continue; }
        
        let walker = WalkDir::new(root).max_depth(3).into_iter().filter_entry(|e| {
            let name = e.file_name().to_string_lossy();
            !["node_modules", "target", "__pycache__", ".git"].contains(&name.as_ref())
        });

        for entry in walker.filter_map(|e| e.ok()) {
            let p = entry.path();
            if let Some(info) = get_venv_info(p) {
                if !registered_paths.contains(&info.path) {
                    untracked_venvs.push(info);
                }
            }
        }
    }

    AuditReport { broken_links, untracked_venvs }
}

#[tauri::command]
fn check_managers() -> ManagerStatus {
    let mut uv = false;
    let mut poetry = false;
    let mut pdm = false;

    // 1. First, check standard PATH
    if Command::new("uv").arg("--version").output().is_ok() { uv = true; }
    if Command::new("poetry").arg("--version").output().is_ok() { poetry = true; }
    if Command::new("pdm").arg("--version").output().is_ok() { pdm = true; }

    // 2. Comprehensive search in common directories
    if !uv || !poetry || !pdm {
        let mut search_dirs = vec![
            PathBuf::from("/usr/local/bin"),
            PathBuf::from("/usr/bin"),
            PathBuf::from("/bin"),
        ];

        if let Some(home) = dirs::home_dir() {
            search_dirs.push(home.join(".local").join("bin"));
            search_dirs.push(home.join(".cargo").join("bin"));
            search_dirs.push(home.join("bin"));
            search_dirs.push(home.join(".local").join("share").join("uv").join("bin")); // specific uv path
        }

        for dir in search_dirs {
            if !uv && dir.join("uv").exists() { 
                if Command::new(dir.join("uv")).arg("--version").output().is_ok() { uv = true; }
            }
            if !poetry && dir.join("poetry").exists() {
                if Command::new(dir.join("poetry")).arg("--version").output().is_ok() { poetry = true; }
            }
            if !pdm && dir.join("pdm").exists() {
                if Command::new(dir.join("pdm")).arg("--version").output().is_ok() { pdm = true; }
            }
        }
    }

    println!("EXHAUSTIVE CHECK: uv:{}, poetry:{}, pdm:{}", uv, poetry, pdm);
    ManagerStatus { uv, poetry, pdm }
}

fn get_manager_path(cmd: &str) -> String {
    // Check global PATH
    if Command::new(cmd).arg("--version").output().is_ok() {
        return cmd.to_string();
    }

    // Search manually
    if let Some(home) = dirs::home_dir() {
        let paths = [
            home.join(".local").join("bin").join(cmd),
            home.join(".cargo").join("bin").join(cmd),
            home.join("bin").join(cmd),
            PathBuf::from("/usr/local/bin").join(cmd),
        ];
        for p in paths {
            if p.exists() && Command::new(&p).arg("--version").output().is_ok() {
                return p.to_string_lossy().to_string();
            }
        }
    }
    cmd.to_string()
}

#[tauri::command]
fn create_venv(path: String, name: String, python_bin: String, engine: String) -> Result<String, String> {
    let mut full_path = PathBuf::from(&path);
    full_path.push(&name);
    let target_path = full_path.to_str().unwrap();

    if engine == "uv" {
        let uv_path = get_manager_path("uv");
        let mut cmd = Command::new(uv_path);
        cmd.args(["venv", target_path]);
        if !python_bin.is_empty() { cmd.arg("--python").arg(&python_bin); }
        let output = cmd.output().map_err(|e| e.to_string())?;
        if output.status.success() { return Ok(format!("Created with uv: {}", name)); }
        else { return Err(String::from_utf8_lossy(&output.stderr).to_string()); }
    }
    // ...

    let bin = if python_bin.is_empty() { "python3".to_string() } else { python_bin };
    let output = Command::new(bin).args(["-m", "venv", target_path]).output().map_err(|e| e.to_string())?;
    if output.status.success() { Ok(format!("Created with venv: {}", name)) } 
    else { Err(String::from_utf8_lossy(&output.stderr).to_string()) }
}

#[tauri::command]
fn delete_venv(path: String) -> Result<String, String> {
    let p = PathBuf::from(&path);
    if p.exists() { fs::remove_dir_all(&p).map_err(|e| format!("Delete failed: {}", e))?; Ok(format!("Deleted {}", path)) } else { Err("Not found".into()) }
}

#[tauri::command]
fn install_dependency(venv_path: String, package: String, engine: String) -> Result<String, String> {
    if engine == "uv" {
        let uv_path = get_manager_path("uv");
        let python_path = get_python_path(Path::new(&venv_path));
        let output = Command::new(uv_path)
            .args(["pip", "install", "--python", python_path.to_str().unwrap(), &package])
            .output().map_err(|e| e.to_string())?;
        if output.status.success() { return Ok(format!("uv installed {}", package)); }
        else { return Err(String::from_utf8_lossy(&output.stderr).to_string()); }
    }

    let p = get_pip_path(Path::new(&venv_path));
    let output = Command::new(p).args(["install", &package]).output().map_err(|e| e.to_string())?;
    if output.status.success() { Ok(format!("Installed {}", package)) } else { Err(String::from_utf8_lossy(&output.stderr).to_string()) }
}

#[tauri::command]
fn uninstall_package(venv_path: String, package: String, engine: String) -> Result<String, String> {
    if engine == "uv" {
        let uv_path = get_manager_path("uv");
        let python_path = get_python_path(Path::new(&venv_path));
        let out = Command::new(uv_path)
            .args(["pip", "uninstall", "--python", python_path.to_str().unwrap(), "-y", &package])
            .output().map_err(|e| e.to_string())?;
        if out.status.success() { return Ok(format!("uv uninstalled {}", package)); }
        else { return Err(String::from_utf8_lossy(&out.stderr).to_string()); }
    }

    let pip = get_pip_path(Path::new(&venv_path));
    let out = Command::new(pip).args(["uninstall", "-y", &package]).output().map_err(|e| e.to_string())?;
    if out.status.success() { Ok(format!("Uninstalled {}", package)) } else { Err(String::from_utf8_lossy(&out.stderr).to_string()) }
}

#[tauri::command]
fn update_package(venv_path: String, package: String, engine: String) -> Result<String, String> {
    if engine == "uv" {
        let uv_path = get_manager_path("uv");
        let python_path = get_python_path(Path::new(&venv_path));
        let out = Command::new(uv_path)
            .args(["pip", "install", "--upgrade", "--python", python_path.to_str().unwrap(), &package])
            .output().map_err(|e| e.to_string())?;
        if out.status.success() { return Ok(format!("uv updated {}", package)); }
        else { return Err(String::from_utf8_lossy(&out.stderr).to_string()); }
    }

    let pip = get_pip_path(Path::new(&venv_path));
    let out = Command::new(pip).args(["install", "--upgrade", &package]).output().map_err(|e| e.to_string())?;
    if out.status.success() { Ok(format!("Updated {}", package)) } else { Err(String::from_utf8_lossy(&out.stderr).to_string()) }
}

#[tauri::command]
fn get_venv_details(path: String) -> Result<VenvDetails, String> {
    let p = PathBuf::from(&path);
    let size_bytes = fs_extra::dir::get_size(&p).unwrap_or(0);
    let size_mb = (size_bytes as f64) / 1024.0 / 1024.0;
    let pip = get_pip_path(&p);
    let mut packages = Vec::new();
    if let Ok(output) = Command::new(pip).args(["list", "--format=freeze"]).output() {
        packages = String::from_utf8_lossy(&output.stdout).lines().map(|s| s.to_string()).collect();
    }
    Ok(VenvDetails { packages, size_mb })
}

#[tauri::command]
fn purge_pip_cache() -> Result<String, String> {
    let out = Command::new("python3").args(["-m", "pip", "cache", "purge"]).output().map_err(|e| e.to_string())?;
    if out.status.success() { Ok("Pip cache cleared".into()) } else { Err(String::from_utf8_lossy(&out.stderr).to_string()) }
}

#[tauri::command]
async fn export_requirements(venv_path: String) -> Result<String, String> {
    let pip = get_pip_path(Path::new(&venv_path));
    let pb = PathBuf::from(&venv_path);
    let project_root = pb.parent().unwrap_or(Path::new(&venv_path));
    let req_path = project_root.join("requirements.txt");
    let out = Command::new(pip).args(["freeze"]).output().map_err(|e| e.to_string())?;
    if out.status.success() {
        fs::write(&req_path, out.stdout).map_err(|e| e.to_string())?;
        Ok(format!("Exported to {}", req_path.to_string_lossy()))
    } else { Err(String::from_utf8_lossy(&out.stderr).to_string()) }
}

#[tauri::command]
async fn search_pypi(query: String) -> Result<serde_json::Value, String> {
    let url = format!("https://pypi.org/pypi/{}/json", query);
    let resp = reqwest::get(url).await.map_err(|e| e.to_string())?;
    if resp.status().is_success() { Ok(resp.json().await.map_err(|e| e.to_string())?) } else { Err("Not found".into()) }
}

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    let migrations = vec![
        Migration { version: 1, description: "init", sql: "CREATE TABLE workspaces (id INTEGER PRIMARY KEY AUTOINCREMENT, path TEXT UNIQUE); CREATE TABLE venvs (id INTEGER PRIMARY KEY AUTOINCREMENT, workspace_path TEXT, name TEXT, path TEXT UNIQUE, version TEXT, status TEXT, issue TEXT);", kind: MigrationKind::Up },
        Migration { version: 2, description: "last_mod", sql: "ALTER TABLE venvs ADD COLUMN last_modified INTEGER DEFAULT 0;", kind: MigrationKind::Up },
        Migration { version: 3, description: "scripts", sql: "CREATE TABLE scripts (id INTEGER PRIMARY KEY AUTOINCREMENT, venv_path TEXT, name TEXT, command TEXT);", kind: MigrationKind::Up },
        Migration { version: 4, description: "custom_templates", sql: "CREATE TABLE custom_templates (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT UNIQUE, packages TEXT);", kind: MigrationKind::Up },
        Migration { version: 5, description: "orchestrator_fields", sql: "ALTER TABLE venvs ADD COLUMN manager_type TEXT DEFAULT 'pip'; ALTER TABLE venvs ADD COLUMN pyproject_path TEXT;", kind: MigrationKind::Up },
        Migration { version: 6, description: "default_workspace", sql: "ALTER TABLE workspaces ADD COLUMN is_default INTEGER DEFAULT 0;", kind: MigrationKind::Up }
    ];
    tauri::Builder::default()
        .plugin(tauri_plugin_sql::Builder::default().add_migrations("sqlite:py-manager.db", migrations).build())
        .plugin(tauri_plugin_fs::init())
        .plugin(tauri_plugin_dialog::init())
        .plugin(tauri_plugin_opener::init())
        .invoke_handler(tauri::generate_handler![
            get_package_sizes, generate_docker_files, check_managers, audit_environments,
            check_venv_health, list_outdated_packages, scan_venv, run_venv_script, read_env_file, save_env_file, 
            open_terminal, open_in_vscode, create_venv, list_venvs, delete_venv, 
            install_dependency, get_venv_details, list_system_pythons, uninstall_package, update_package, purge_pip_cache,
            export_requirements, get_pyvenv_cfg, search_pypi
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
